from lib.forum_engine import Template
from lib.network_tools import NetworkTools

class Crawler(Template):
	NETWORK_TOOLS = NetworkTools(use_proxy=False)
	TEMPLATE = "crawler.arct"
	TEST_TEMPLATE = "crawler_test.arct"
	DB_SERVER_ADDRESS = "mongo:27017"
	DB_SERVER_NAME = "abs-cbn"
	CRAWLER_NAME = "Abs-cbn Crawler"
	LINK_TO_CRAWL = [
		"http://forums.abs-cbn.com/welcome-kapamilya!-236/",
		"http://forums.abs-cbn.com/official-announcements-108/",
		"http://forums.abs-cbn.com/abs-programming-announcements/",
		"http://forums.abs-cbn.com/abs-forum-announcements/'" 
		"http://forums.abs-cbn.com/fpj's-ang-probinsyano/",
		"http://forums.abs-cbn.com/dolce-amore/",
		"http://forums.abs-cbn.com/born-for-you/",
		"http://forums.abs-cbn.com/tubig-at-langis/",
		"http://forums.abs-cbn.com/be-my-lady/",
		"http://forums.abs-cbn.com/doble-kara/",
		"http://forums.abs-cbn.com/maalaala-mo-kaya/",
		"http://forums.abs-cbn.com/wansapanataym/",
		"http://forums.abs-cbn.com/263/",
		"http://forums.abs-cbn.com/general-teleserye-talk/",
		"http://forums.abs-cbn.com/upcoming-teleseryes/",
		"http://forums.abs-cbn.com/langit-lupa/",
		"http://forums.abs-cbn.com/the-greatest-love/",
		"http://forums.abs-cbn.com/till-i-met-you/",
		"http://forums.abs-cbn.com/the-second-wife/",
		"http://forums.abs-cbn.com/because-you-love-me/",
		"http://forums.abs-cbn.com/the-promise-of-forever/",
		"http://forums.abs-cbn.com/never-ever-say-goodbye/",
		"http://forums.abs-cbn.com/written-in-our-stars/",
		"http://forums.abs-cbn.com/someone-to-watch-over-me/",
		"http://forums.abs-cbn.com/darna/",
		"http://forums.abs-cbn.com/captain-barbell/",
		"http://forums.abs-cbn.com/teleserye-archives/",
		"http://forums.abs-cbn.com/shelved-teleseryes/",
		"http://forums.abs-cbn.com/wansapanatym-archives/",
		"http://forums.abs-cbn.com/archives-pre-2000/",
		"http://forums.abs-cbn.com/archives-2000-2009/",
		"http://forums.abs-cbn.com/archives-2010/",
		"http://forums.abs-cbn.com/archives-2011/",
		"http://forums.abs-cbn.com/archives-2012/",
		"http://forums.abs-cbn.com/archives-2013/",
		"http://forums.abs-cbn.com/archives-2014/",
		"http://forums.abs-cbn.com/archives-2015/",
		"http://forums.abs-cbn.com/ningning/",
		"http://forums.abs-cbn.com/all-of-me/",
		"http://forums.abs-cbn.com/pangako-sayo-(2015)/",
		"http://forums.abs-cbn.com/pasion-de-amor/",
		"http://forums.abs-cbn.com/on-the-wings-of-love/",
		"http://forums.abs-cbn.com/and-i-love-you-so/",
		"http://forums.abs-cbn.com/you're-my-home-(2015)/",
		"http://forums.abs-cbn.com/the-story-of-us/",
		"http://forums.abs-cbn.com/we-will-survive/",
		"http://forums.abs-cbn.com/super-d/",
		"http://forums.abs-cbn.com/pinoy-big-brother-lucky-7/",
		"http://forums.abs-cbn.com/pbb7-official-housemates/",
		"http://forums.abs-cbn.com/minute-to-win-it-season-2/",
		"http://forums.abs-cbn.com/the-voice-kids-season-3/",
		"http://forums.abs-cbn.com/we-love-opm-the-celebrity-sing-offs/",
		"http://forums.abs-cbn.com/family-feud/",
		"http://forums.abs-cbn.com/mga-kwento-ni-marc-logan/",
		"http://forums.abs-cbn.com/general-reality-game-show-talk/",
		"http://forums.abs-cbn.com/upcoming-reality-game-shows/",
		"http://forums.abs-cbn.com/pinoy-boyband-superstar/",
		"http://forums.abs-cbn.com/dance-teens/",
		"http://forums.abs-cbn.com/406/",
		"http://forums.abs-cbn.com/dance-kids-season-2/",
		"http://forums.abs-cbn.com/pilipinas-got-talent-season-6/",
		"http://forums.abs-cbn.com/i-do-season-2/",
		"http://forums.abs-cbn.com/reality-game-show-archives/",
		"http://forums.abs-cbn.com/general-discussion/",
		"http://forums.abs-cbn.com/pilipinas-got-talent-season-4/",
		"http://forums.abs-cbn.com/i-shine-talent-camp-2/",
		"http://forums.abs-cbn.com/kapamilya-deal-or-no-deal/",
		"http://forums.abs-cbn.com/the-voice-philippines/",
		"http://forums.abs-cbn.com/i-dare-you-season-2/",
		"http://forums.abs-cbn.com/minute-to-win-it/",
		"http://forums.abs-cbn.com/the-biggest-loser-doubles/",
		"http://forums.abs-cbn.com/bet-on-your-baby/",
		"http://forums.abs-cbn.com/the-voice-of-the-philippines-kids-edition/",
		"http://forums.abs-cbn.com/pinoy-big-brother-season-5/",
		"http://forums.abs-cbn.com/i-do/",
		"http://forums.abs-cbn.com/the-singing-bee/",
		"http://forums.abs-cbn.com/bet-on-your-baby-season-2/",
		"http://forums.abs-cbn.com/the-voice-of-the-philippines-season-2/",
		"http://forums.abs-cbn.com/your-face-sounds-familiar/",
		"http://forums.abs-cbn.com/voice-kids-season-2/",
		"http://forums.abs-cbn.com/pinoy-big-brother-10/",
		"http://forums.abs-cbn.com/your-face-sounds-familiar-season-2/",
		"http://forums.abs-cbn.com/dance-kids/",
		"http://forums.abs-cbn.com/kapamilya-deal-or-no-deal-(2015)/",
		"http://forums.abs-cbn.com/celebrity-playtime/",
		"http://forums.abs-cbn.com/game-ng-bayan-(march-7-2015-present)/",
		"http://forums.abs-cbn.com/i-love-opm-original-pinoy-music/",
		"http://forums.abs-cbn.com/pilipinas-got-talent-season-5/",
		"http://forums.abs-cbn.com/its-showtime/",
		"http://forums.abs-cbn.com/its-showtime-hosts/",
		"http://forums.abs-cbn.com/its-showtime-segments/",
		"http://forums.abs-cbn.com/it's-showtime-retired-segments/",
		"http://forums.abs-cbn.com/it's-showtime-former-co-hosts/",
		"http://forums.abs-cbn.com/asap-2012/",
		"http://forums.abs-cbn.com/upcoming-variety-shows/",
		"http://forums.abs-cbn.com/variety-show-archives/",
		"http://forums.abs-cbn.com/sarah-g-live/",
		"http://forums.abs-cbn.com/general-tv-talk/",
		"http://forums.abs-cbn.com/general-tv-headlines-ratings/",
		"http://forums.abs-cbn.com/banana-split/",
		"http://forums.abs-cbn.com/home-sweetie-home/",
		"http://forums.abs-cbn.com/goin'-bulilit/",
		"http://forums.abs-cbn.com/general-comedy-talk/",
		"http://forums.abs-cbn.com/upcoming-comedies/",
		"http://forums.abs-cbn.com/palibhasa-lalake-(2016)/",
		"http://forums.abs-cbn.com/toda-max/",
		"http://forums.abs-cbn.com/luv-u/",
		"http://forums.abs-cbn.com/comedy-show-archives/",
		"http://forums.abs-cbn.com/martin-late-night/",
		"http://forums.abs-cbn.com/kwentong-kusina/",
		"http://forums.abs-cbn.com/showbiz-inside-report/",
		"http://forums.abs-cbn.com/the-buzz/",
		"http://forums.abs-cbn.com/aquino-abunda-tonight/",
		"http://forums.abs-cbn.com/kris-tv/",
		"http://forums.abs-cbn.com/magandang-buhay-(april-18-2016-present)/",
		"http://forums.abs-cbn.com/tonight-with-boy-abunda/",
		"http://forums.abs-cbn.com/gandang-gabi-vice!/",
		"http://forums.abs-cbn.com/general-talk-shows-forum/",
		"http://forums.abs-cbn.com/talk-show-archives/",
		"http://forums.abs-cbn.com/tv-patrol-25/",
		"http://forums.abs-cbn.com/umagang-kay-ganda/",
		"http://forums.abs-cbn.com/rated-k/",
		"http://forums.abs-cbn.com/bandila/",
		"http://forums.abs-cbn.com/failon-ngayon/",
		"http://forums.abs-cbn.com/the-bottomline-with-boy-abunda/",
		"http://forums.abs-cbn.com/s-o-c-o-(scene-of-the-crime-operatives)/",
		"http://forums.abs-cbn.com/storyline/",
		"http://forums.abs-cbn.com/matanglawin/",
		"http://forums.abs-cbn.com/kabuhayang-swak-na-swak/",
		"http://forums.abs-cbn.com/salamat-dok!/",
		"http://forums.abs-cbn.com/sports-unlimited/",
		"http://forums.abs-cbn.com/infotainment/",
		"http://forums.abs-cbn.com/news-current-affairs-archives/",
		"http://forums.abs-cbn.com/trip-na-trip/",
		"http://forums.abs-cbn.com/pinoy-true-stories/",
		"http://forums.abs-cbn.com/ako-ang-simula/",
		"http://forums.abs-cbn.com/patrol-ng-pilipino/",
		"http://forums.abs-cbn.com/xxx-exklusibong-explosibong-expose/",
		"http://forums.abs-cbn.com/krusada/",
		"http://forums.abs-cbn.com/japanese-anime/",
		"http://forums.abs-cbn.com/haikyu!!-(!!)/",
		"http://forums.abs-cbn.com/naruto-shippuden-(-)/",
		"http://forums.abs-cbn.com/the-flying-house-()/",
		"http://forums.abs-cbn.com/kuroko's-basketball-season-2-()/",
		"http://forums.abs-cbn.com/general-anime-discussions/",
		"http://forums.abs-cbn.com/anime-archives/",
		"http://forums.abs-cbn.com/marcelino-pan-y-vino/",
		"http://forums.abs-cbn.com/princess-sarah/",
		"http://forums.abs-cbn.com/dog-of-flanders-()/",
		"http://forums.abs-cbn.com/cedie-ang-munting-prinsipe/",
		"http://forums.abs-cbn.com/remi-nobody's-girl-()/",
		"http://forums.abs-cbn.com/cartoons/",
		"http://forums.abs-cbn.com/kung-fu-panda-legends-of-awesomeness/",
		"http://forums.abs-cbn.com/spongebob-squarepants/",
		"http://forums.abs-cbn.com/superbook-classics/",
		"http://forums.abs-cbn.com/general-cartoon-discussions/",
		"http://forums.abs-cbn.com/cartoon-archives/",
		"http://forums.abs-cbn.com/my-giant-friend/",
		"http://forums.abs-cbn.com/max-steel/",
		"http://forums.abs-cbn.com/jimmy-neutron/",
		"http://forums.abs-cbn.com/asianovela-archives/",
		"http://forums.abs-cbn.com/asian-films/",
		"http://forums.abs-cbn.com/asian-stars/",
		"http://forums.abs-cbn.com/upcoming-asianovelas/",
		"http://forums.abs-cbn.com/good-doctor-(-)/",
		"http://forums.abs-cbn.com/asianovela-general-discussions/",
		"http://forums.abs-cbn.com/tfc-general-discussions/",
		"http://forums.abs-cbn.com/tfc-programs/",
		"http://forums.abs-cbn.com/asianovela-archives-a-m/",
		"http://forums.abs-cbn.com/asianovela-archives-n-z/",
		"http://forums.abs-cbn.com/tfc-channels/",
		"http://forums.abs-cbn.com/tfc-connect/",
		"http://forums.abs-cbn.com/tfc-subtitled-series/",
		"http://forums.abs-cbn.com/adobo-nation/",
		"http://forums.abs-cbn.com/balitang-worldwide/",
		"http://forums.abs-cbn.com/barangay-usa/",
		"http://forums.abs-cbn.com/409/",
		"http://forums.abs-cbn.com/citizen-pinoy/",
		"http://forums.abs-cbn.com/ohh-la-lam/",
		"http://forums.abs-cbn.com/pinoy-destinations/",
		"http://forums.abs-cbn.com/tfc-show-archives/",
		"http://forums.abs-cbn.com/studio-23-general-discussions/",
		"http://forums.abs-cbn.com/abs-cbn-sportsaction-programs/",
		"http://forums.abs-cbn.com/cinema-one-global/",
		"http://forums.abs-cbn.com/myx-tv/",
		"http://forums.abs-cbn.com/bro/",
		"http://forums.abs-cbn.com/lifestyle-channel/",
		"http://forums.abs-cbn.com/studio-23-archives/",
		"http://forums.abs-cbn.com/jeepney-tv-general-discussions/",
		"http://forums.abs-cbn.com/jeepney-tv-programs/",
		"http://forums.abs-cbn.com/star-cinema/",
		"http://forums.abs-cbn.com/cinema-one/",
		"http://forums.abs-cbn.com/kapamilya-films/",
		"http://forums.abs-cbn.com/general-movies-talk/",
		"http://forums.abs-cbn.com/other-filipino-films/",
		"http://forums.abs-cbn.com/foreign-films/",
		"http://forums.abs-cbn.com/star-cinema-archives/",
		"http://forums.abs-cbn.com/telenovelas-general-discussions/",
		"http://forums.abs-cbn.com/telenovela-arvhives/",
		"http://forums.abs-cbn.com/news/",
		"http://forums.abs-cbn.com/the-score/",
		"http://forums.abs-cbn.com/jane-the-virgin-(tagalized)/",
		"http://forums.abs-cbn.com/international-shows-general-discussions/",
		"http://forums.abs-cbn.com/female-kapamilya-stars/",
		"http://forums.abs-cbn.com/kapamilya-male-stars/",
		"http://forums.abs-cbn.com/kapamilya-loveteams/",
		"http://forums.abs-cbn.com/star-records/",
		"http://forums.abs-cbn.com/myx/",
		"http://forums.abs-cbn.com/general-music-forum/",
		"http://forums.abs-cbn.com/mor-101-9/",
		"http://forums.abs-cbn.com/dzmm/",
		"http://forums.abs-cbn.com/national/",
		"http://forums.abs-cbn.com/metro/",
		"http://forums.abs-cbn.com/business/",
		"http://forums.abs-cbn.com/world/",
		"http://forums.abs-cbn.com/opinion/",
		"http://forums.abs-cbn.com/official-announcements/",
		"http://forums.abs-cbn.com/love-relationships/",
		"http://forums.abs-cbn.com/technology-internet/",
		"http://forums.abs-cbn.com/clothing-fashion-trends/",
		"http://forums.abs-cbn.com/sports/",
		"http://forums.abs-cbn.com/ask-the-moderators/",
		"http://forums.abs-cbn.com/ana-manuela/"
        ]
	COUNTRY = "PHL"
	THREAD_XPATH = "//span[re:test(@id,'msg_*')]"
	THREAD_LINK_XPATH = "./a/@href"
	LAST_PAGE_XPATH = "//div[@class='pagelinks floatleft']/a[@class='navPages'][last()]/@href"
	PREV_XPATH = "//div[@class='pagelinks floatleft']/strong/preceding-sibling::a[@class='navPages'][1]/@href"
	POST_XPATH = "//form[@id='quickModForm']//div[@class='windowbg' or @class='windowbg2']"
	FIELDS = [ 
		{"published_date": {
			"single": True,
			"data_type": "date",
			"concat": True,
			"xpath":".//h5[re:test(@id,'subject_*')]/following-sibling::div[1]/text()"
		}},
		{"author_name":{
			"single":True,
			"data_type": "string",
			"concat":True,
			"xpath": ".//div[@class='poster']/h4//text()"
		}},
		{"content":{
			"single":True,
			"data_type": "string",
			"concat":True,
			"xpath":".//div[@class='post']/div[re:test(@id,'msg_*')]//text()"
		}},
		{"permalink": {
			"single": True,
			"data_type": "url",
			"concat": False,
			"xpath": ".//h5[re:test(@id,'subject_*')]/a/@href"
		}},
		{"title":{
			"single":True,
			"data_type": "string",
			"concat":False,
			"xpath":"//div[@class='navigate_section']//li[@class='last']/a//text()"
		}}       
	]
	CONDITIONS={
		"has_to_have_content":{
			"condition":'"content" in document',
			"exception":'"Content is not defined"'
		},
		"content_cannot_be_empty":{
			"condition":'len(document["content"]) > 0',
			"exception":'"Content cannot be empty"'
		}
	}
#end class
