from lib.forum_engine import Template
from lib.network_tools import NetworkTools

class Crawler(Template):
	NETWORK_TOOLS = NetworkTools(use_proxy=False)
	TEMPLATE = "crawler.arct"
	TEST_TEMPLATE = "crawler_test.arct"
	DB_SERVER_ADDRESS = "mongo:27017"
	DB_SERVER_NAME = "gearheads"
	CRAWLER_NAME = "Gearheads Crawler"
	LINK_TO_CRAWL = [
		"http://gearheads.in./forumdisplay.php?5-Announcements-amp-FAQ-s",
		"http://gearheads.in./forumdisplay.php?4-Introduce-Yourself",
		"http://gearheads.in./forumdisplay.php?292-Automotive-News-amp-General-Discussions",
		"http://gearheads.in./forumdisplay.php?283-What-Car-do-I-buy",
		"http://gearheads.in./forumdisplay.php?22-Hatchbacks",
		"http://gearheads.in./forumdisplay.php?23-Sedans",
		"http://gearheads.in./forumdisplay.php?24-SUV-s-amp-4x4-s",
		"http://gearheads.in./forumdisplay.php?25-Luxury-Cars",
		"http://gearheads.in./forumdisplay.php?272-Shootouts",
		"http://gearheads.in./forumdisplay.php?18-Technical-Discussions",
		"http://gearheads.in./forumdisplay.php?54-Engines-amp-Transmissions",
		"http://gearheads.in./forumdisplay.php?55-Bodywork-amp-Interiors",
		"http://gearheads.in./forumdisplay.php?289-Automotive-Lighting",
		"http://gearheads.in./forumdisplay.php?56-Electricals-amp-Electronics",
		"http://gearheads.in./forumdisplay.php?57-Alloys-amp-Tyres",
		"http://gearheads.in./forumdisplay.php?58-Handling-(Suspension-Steering-Brakes-etc)",
		"http://gearheads.in./forumdisplay.php?336-Product-Announcements",
		"http://gearheads.in./forumdisplay.php?284-ICE-Forums",
		"http://gearheads.in./forumdisplay.php?20-ICE-News-amp-General-Discussions",
		"http://gearheads.in./forumdisplay.php?88-Equipment-amp-Install-Queries",
		"http://gearheads.in./forumdisplay.php?89-Build-and-Installs",
		"http://gearheads.in./forumdisplay.php?333-Product-Announcements",
		"http://gearheads.in./forumdisplay.php?318-Home-Audio-Video",
		"http://gearheads.in./forumdisplay.php?308-General-Discussions",
		"http://gearheads.in./forumdisplay.php?309-Show-Room",
		"http://gearheads.in./forumdisplay.php?310-Detailing-Guide-Book",
		"http://gearheads.in./forumdisplay.php?311-Product-Reviews",
		"http://gearheads.in./forumdisplay.php?312-Detailing-Doubts",
		"http://gearheads.in./forumdisplay.php?331-Product-Announcements",
		"http://gearheads.in./forumdisplay.php?319-Indian-Car-Sales-Reports-and-Analysis&",
		"http://gearheads.in./forumdisplay.php?105-Maruti",
		"http://gearheads.in./forumdisplay.php?322-Celerio",
		"http://gearheads.in./forumdisplay.php?344-Baleno",
		"http://gearheads.in./forumdisplay.php?330-Ciaz",
		"http://gearheads.in./forumdisplay.php?340-S-Cross",
		"http://gearheads.in./forumdisplay.php?343-Vitara-Brezza",
		"http://gearheads.in./forumdisplay.php?165-Swift",
		"http://gearheads.in./forumdisplay.php?164-Ritz",
		"http://gearheads.in./forumdisplay.php?161-Alto",
		"http://gearheads.in./forumdisplay.php?259-WagonR",
		"http://gearheads.in./forumdisplay.php?158-M800",
		"http://gearheads.in./forumdisplay.php?159-Omni",
		"http://gearheads.in./forumdisplay.php?162-Estilo",
		"http://gearheads.in./forumdisplay.php?163-A-Star",
		"http://gearheads.in./forumdisplay.php?251-Gypsy",
		"http://gearheads.in./forumdisplay.php?167-SX-4",
		"http://gearheads.in./forumdisplay.php?168-Grand-Vitara",
		"http://gearheads.in./forumdisplay.php?258-Kizashi",
		"http://gearheads.in./forumdisplay.php?323-Eeco",
		"http://gearheads.in./forumdisplay.php?173-Dealers",
		"http://gearheads.in./forumdisplay.php?169-Discontinued",
		"http://gearheads.in./forumdisplay.php?171-Zen",
		"http://gearheads.in./forumdisplay.php?172-Baleno",
		"http://gearheads.in./forumdisplay.php?301-Esteem"
		"http://gearheads.in./forumdisplay.php?107-Ford",
		"http://gearheads.in./forumdisplay.php?115-Figo",
		"http://gearheads.in./forumdisplay.php?117-Endeavour",
		"http://gearheads.in./forumdisplay.php?262-EcoSport",
		"http://gearheads.in./forumdisplay.php?118-Discontinued",
		"http://gearheads.in./forumdisplay.php?116-Fiesta",
		"http://gearheads.in./forumdisplay.php?129-Dealers",
		"http://gearheads.in./forumdisplay.php?341-Aspire",
		"http://gearheads.in./forumdisplay.php?108-Hyundai",
		"http://gearheads.in./forumdisplay.php?144-Verna",
		"http://gearheads.in./forumdisplay.php?339-Creta",
		"http://gearheads.in./forumdisplay.php?141-Santro",
		"http://gearheads.in./forumdisplay.php?248-Getz",
		"http://gearheads.in./forumdisplay.php?253-Tucson",
		"http://gearheads.in./forumdisplay.php?253-Tucson",
		"http://gearheads.in./forumdisplay.php?148-Santa-Fe",
		"http://gearheads.in./forumdisplay.php?142-i10",
		"http://gearheads.in./forumdisplay.php?255-Terracan",
		"http://gearheads.in./forumdisplay.php?175-Dealers",
		"http://gearheads.in./forumdisplay.php?143-i20",
		"http://gearheads.in./forumdisplay.php?146-Sonata",
		"http://gearheads.in./forumdisplay.php?145-Elantra",
		"http://gearheads.in./forumdisplay.php?147-Accent",
		"http://gearheads.in./forumdisplay.php?240-Tata",
		"http://gearheads.in./forumdisplay.php?264-Aria",
		"http://gearheads.in./forumdisplay.php?241-Indica-Vista",
		"http://gearheads.in./forumdisplay.php?293-Sumo",
		"http://gearheads.in./forumdisplay.php?346-Tiago",
		"http://gearheads.in./forumdisplay.php?249-Nano",
		"http://gearheads.in./forumdisplay.php?328-Zest",
		"http://gearheads.in./forumdisplay.php?243-Safari-Storme",
		"http://gearheads.in./forumdisplay.php?244-Dealers",
		"http://gearheads.in./forumdisplay.php?242-Indigo-Manza",
		"http://gearheads.in./forumdisplay.php?252-Sierra",
		"http://gearheads.in./forumdisplay.php?177-Honda",
		"http://gearheads.in./forumdisplay.php?345-BR-V",
		"http://gearheads.in./forumdisplay.php?297-ANHC",
		"http://gearheads.in./forumdisplay.php?327-Mobilio",
		"http://gearheads.in./forumdisplay.php?178-OHC",
		"http://gearheads.in./forumdisplay.php?183-Civic",
		"http://gearheads.in./forumdisplay.php?182-Jazz",
		"http://gearheads.in./forumdisplay.php?305-Amaze",
		"http://gearheads.in./forumdisplay.php?184-Accord",
		"http://gearheads.in./forumdisplay.php?185-CR-V",
		"http://gearheads.in./forumdisplay.php?180-NHC",
		"http://gearheads.in./forumdisplay.php?181-Brio",
		"http://gearheads.in./forumdisplay.php?186-Dealers",
		"http://gearheads.in./forumdisplay.php?113-Chevrolet",
		"http://gearheads.in./forumdisplay.php?135-Cruze",
		"http://gearheads.in./forumdisplay.php?134-Optra-Magnum",
		"http://gearheads.in./forumdisplay.php?138-Tavera",
		"http://gearheads.in./forumdisplay.php?131-Beat",
		"http://gearheads.in./forumdisplay.php?325-Enjoy",
		"http://gearheads.in./forumdisplay.php?132-Spark",
		"http://gearheads.in./forumdisplay.php?136-Aveo",
		"http://gearheads.in./forumdisplay.php?176-Dealers",
		"http://gearheads.in./forumdisplay.php?133-Aveo-Sail-U-VA",
		"http://gearheads.in./forumdisplay.php?137-Captiva",
		"http://gearheads.in./forumdisplay.php?106-Mahindra",
		"http://gearheads.in./forumdisplay.php?153-XUV-500",
		"http://gearheads.in./forumdisplay.php?156-Reva",
		"http://gearheads.in./forumdisplay.php?151-Scorpio",
		"http://gearheads.in./forumdisplay.php?154-Verito",
		"http://gearheads.in./forumdisplay.php?250-Jeeps",
		"http://gearheads.in./forumdisplay.php?150-Bolero",
		"http://gearheads.in./forumdisplay.php?155-Xylo",
		"http://gearheads.in./forumdisplay.php?174-Dealers",
		"http://gearheads.in./forumdisplay.php?152-Thar",
		"http://gearheads.in./forumdisplay.php?291-Quanto",
		"http://gearheads.in./forumdisplay.php?195-Fiat",
		"http://gearheads.in./forumdisplay.php?197-Punto",
		"http://gearheads.in./forumdisplay.php?237-Dealers",
		"http://gearheads.in./forumdisplay.php?198-Linea",
		"http://gearheads.in./forumdisplay.php?199-Palio",
		"http://gearheads.in./forumdisplay.php?200-Sienna",
		"http://gearheads.in./forumdisplay.php?217-Volkswagen",
		"http://gearheads.in./forumdisplay.php?219-Polo52",
		"http://gearheads.in./forumdisplay.php?223-Beetle",
		"http://gearheads.in./forumdisplay.php?220-Vento",
		"http://gearheads.in./forumdisplay.php?224-Toureg",
		"http://gearheads.in./forumdisplay.php?221-Jetta",
		"http://gearheads.in./forumdisplay.php?225-Phaeton",
		"http://gearheads.in./forumdisplay.php?222-Passat",
		"http://gearheads.in./forumdisplay.php?239-Dealers",
		"http://gearheads.in./forumdisplay.php?201-Renault",
		"http://gearheads.in./forumdisplay.php?203-Fluence",
		"http://gearheads.in./forumdisplay.php?205-Pulse",
		"http://gearheads.in./forumdisplay.php?206-Duster",
		"http://gearheads.in./forumdisplay.php?204-Koleos",
		"http://gearheads.in./forumdisplay.php?338-Lodgy",
		"http://gearheads.in./forumdisplay.php?209-Dealers",
		"http://gearheads.in./forumdisplay.php?342-Kwid",
		"http://gearheads.in./forumdisplay.php?296-Scala",
		"http://gearheads.in./forumdisplay.php?266-Fabia",
		"http://gearheads.in./forumdisplay.php?267-Laura-Octavia",
		"http://gearheads.in./forumdisplay.php?268-Yeti",
		"http://gearheads.in./forumdisplay.php?269-Superb",
		"http://gearheads.in./forumdisplay.php?270-Rapid",
		"http://gearheads.in./forumdisplay.php?277-Skoda-Wiki",
		"http://gearheads.in./forumdisplay.php?234-Innova",
		"http://gearheads.in./forumdisplay.php?228-Liva",
		"http://gearheads.in./forumdisplay.php?230-Corolla-Altis",
		"http://gearheads.in./forumdisplay.php?229-Etios",
		"http://gearheads.in./forumdisplay.php?231-Camry",
		"http://gearheads.in./forumdisplay.php?232-Fortuner",
		"http://gearheads.in./forumdisplay.php?235-Prius",
		"http://gearheads.in./forumdisplay.php?317-Qualis",
		"http://gearheads.in./forumdisplay.php?236-Prado",
		"http://gearheads.in./forumdisplay.php?233-Dealers",
		"http://gearheads.in./forumdisplay.php?337-Terrano",
		"http://gearheads.in./forumdisplay.php?213-Sunny",
		"http://gearheads.in./forumdisplay.php?214-X-Trail",
		"http://gearheads.in./forumdisplay.php?212-Micra",
		"http://gearheads.in./forumdisplay.php?215-Teana",
		"http://gearheads.in./forumdisplay.php?216-370Z",
		"http://gearheads.in./forumdisplay.php?238-Dealers",
		"http://gearheads.in./forumdisplay.php?257-Nissan-Wiki",
		"http://gearheads.in./forumdisplay.php?189-Cedia",
		"http://gearheads.in./forumdisplay.php?190-Montero",
		"http://gearheads.in./forumdisplay.php?194-Lancer",
		"http://gearheads.in./forumdisplay.php?192-Pajero",
		"http://gearheads.in./forumdisplay.php?191-Outlander",
		"http://gearheads.in./forumdisplay.php?193-Evo-X",
		"http://gearheads.in./forumdisplay.php?273-Premier-Sonalika-Force-Motors-etc",
		"http://gearheads.in./forumdisplay.php?271-Imports-and-Luxury-Cars",
		"http://gearheads.in./forumdisplay.php?15-Vintage-amp-Classics",
		"http://gearheads.in./forumdisplay.php?83-Tuner-Garage-Feedback",
		"http://gearheads.in./forumdisplay.php?68-Commercial-Vehicles",
		"http://gearheads.in./forumdisplay.php?82-Boats",
		"http://gearheads.in./forumdisplay.php?299-What-Bike-to-Buy",
		"http://gearheads.in./forumdisplay.php?298-Ownership-Reports",
		"http://gearheads.in./forumdisplay.php?300-Tech-Talk",
		"http://gearheads.in./forumdisplay.php?87-Bicycle",
		"http://gearheads.in./forumdisplay.php?93-Bike-News",
		"http://gearheads.in./forumdisplay.php?95-International-Bike-News",
		"http://gearheads.in./forumdisplay.php?314-General-Discussions",
		"http://gearheads.in./forumdisplay.php?17-Super-Cars-Section",
		"http://gearheads.in./forumdisplay.php?29-RTO-Law-Loans-amp-Insurance",
		"http://gearheads.in./forumdisplay.php?44-Travelogues",
		"http://gearheads.in./forumdisplay.php?307-International-Travelogues",
		"http://gearheads.in./forumdisplay.php?45-Route-Maps-amp-Holiday-Discussions",
		"http://gearheads.in./forumdisplay.php?52-Traffic-Lights",
		"http://gearheads.in./forumdisplay.php?40-F1",
		"http://gearheads.in./forumdisplay.php?39-Track-Racing",
		"http://gearheads.in./forumdisplay.php?46-Drag-Racing",
		"http://gearheads.in./forumdisplay.php?38-Rallying",
		"http://gearheads.in./forumdisplay.php?16-4x4s-and-Off-Road",
		"http://gearheads.in./forumdisplay.php?65-OTR-s",
		"http://gearheads.in./forumdisplay.php?49-Electrical-and-Electronics",
		"http://gearheads.in./forumdisplay.php?90-Reviews",
		"http://gearheads.in./forumdisplay.php?48-Photography",
		"http://gearheads.in./forumdisplay.php?288-Health-and-Wellness",
		"http://gearheads.in./forumdisplay.php?76-Car-and-Bike",
		"http://gearheads.in./forumdisplay.php?77-ICE-and-Gadgets",
		"http://gearheads.in./forumdisplay.php?97-Parts-And-Accessories",
		"http://gearheads.in./forumdisplay.php?78-General",
		"http://gearheads.in./forumdisplay.php?101-Sold-Items-Closed-Trades-Completed-Deals",
		"http://gearheads.in./forumdisplay.php?79-Car-and-Bike",
		"http://gearheads.in./forumdisplay.php?80-ICE-and-Gadgets",
		"http://gearheads.in./forumdisplay.php?98-Parts-And-Accessories",
		"http://gearheads.in./forumdisplay.php?81-General",
		"http://gearheads.in./forumdisplay.php?324-Product-Announcements"
    ]       
	COUNTRY = "IND"
	THREAD_XPATH = "//ol//li[re:test(@id,'thread*')]"
	THREAD_LINK_XPATH = ".//a[@class='title']/@href"
	LAST_PAGE_XPATH = "//span[@class='first_last']/a/@href"
	PREV_XPATH = "//a[@rel='prev']/@href"
	POST_XPATH = "//ol//li[re:test(@id,'post_*')]"
	FIELDS = [
		{"published_date": {
			"single": True, 
			"data_type": "date", 
			"concat": False, 
			"xpath": ".//span[@class='date']//text()"
		}},
		{"permalink": {
			"single": True, 
			"data_type": "url", 
			"concat": False, 
			"xpath": ".//span[@class='nodecontrols']/a/@href"
		}},
		{"author_name":{
			"single":True,
			"data_type": "string",
			"concat":False,
			"xpath":".//a[re:test(@class,'username')]//text()"
		}},
		{"content":{
			"single":True,
			"data_type": "string",
			"concat":True,
			"xpath":".//div[@class='content']//text()"
		}},
		{"title":{
			"single":True,
			"data_type": "string",
			"concat":False,
			"xpath":"//span[@class='threadtitle']//text()"
		}}
	]
	CONDITIONS={
		"has_to_have_content":{
			"condition":'"content" in document',
			"exception":'"Content is not defined"'
		},
		"content_cannot_be_empty":{
			"condition":'len(document["content"]) > 0',
			"exception":'"Content cannot be empty"'
		}
	}
#end class
