from lib.forum_engine import Template
from lib.network_tools import NetworkTools

class Crawler(Template):
     NETWORK_TOOLS = NetworkTools(use_proxy=False)
     TEMPLATE = "crawler.arct"
     TEST_TEMPLATE = "crawler_test.arct"
     DB_SERVER_ADDRESS = "mongo:27017"
     DB_SERVER_NAME = "modifikasi"
     CRAWLER_NAME = "Modifikasi Crawler"
     LINK_TO_CRAWL = [
               "http://www.modifikasi.com/forumdisplay.php/504-Cars-Feature",
               "http://www.modifikasi.com/forumdisplay.php/505-Modcom-Stereo",
               "http://www.modifikasi.com/forumdisplay.php/504-Cars-Feature",
               "http://www.modifikasi.com/forumdisplay.php/505-Modcom-Stereo",
               "http://www.modifikasi.com/forumdisplay.php/502-Komunitas-amp-Event",
               "http://www.modifikasi.com/forumdisplay.php/503-Hotspot-amp-Product",
               "http://www.modifikasi.com/forumdisplay.php/533-GIIAS-2015",
               "http://www.modifikasi.com/forumdisplay.php/153-Otomotif-amp-Official-Modcom-Events",
               "http://www.modifikasi.com/forumdisplay.php/368-Berita-Otomotif-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/369-Berita-Otomotif-Motor",
               "http://www.modifikasi.com/forumdisplay.php/154-Racing-Events",
               "http://www.modifikasi.com/forumdisplay.php/155-Modification-Events",
               "http://www.modifikasi.com/forumdisplay.php/384-Events-Lainnya",
               "http://www.modifikasi.com/forumdisplay.php/343-Modifikasi-com-Photo-Contest-2012",
               "http://www.modifikasi.com/forumdisplay.php/71-Suara-Konsumen",
               "http://www.modifikasi.com/forumdisplay.php/298-Lowongan-Kerja-Otomotif",
               "http://www.modifikasi.com/forumdisplay.php/300-Informasi-Kehilangan-Kendaraan",
               "http://www.modifikasi.com/forumdisplay.php/470-Alfa-Romeo",
               "http://www.modifikasi.com/forumdisplay.php/471-Aston-Martin",
               "http://www.modifikasi.com/forumdisplay.php/144-Audi",
               "http://www.modifikasi.com/forumdisplay.php/472-Bentley",
               "http://www.modifikasi.com/forumdisplay.php/123-BMW",
               "http://www.modifikasi.com/forumdisplay.php/201-Chevrolet",
               "http://www.modifikasi.com/forumdisplay.php/474-Chrysler",
               "http://www.modifikasi.com/forumdisplay.php/475-Citroen",
               "http://www.modifikasi.com/forumdisplay.php/124-Daihatsu",
               "http://www.modifikasi.com/forumdisplay.php/476-Datsun",
               "http://www.modifikasi.com/forumdisplay.php/477-Dodge",
               "http://www.modifikasi.com/forumdisplay.php/478-Ferrari",
               "http://www.modifikasi.com/forumdisplay.php/479-Fiat",
               "http://www.modifikasi.com/forumdisplay.php/125-Ford",
               "http://www.modifikasi.com/forumdisplay.php/480-Geely",
               "http://www.modifikasi.com/forumdisplay.php/481-Holden",
               "http://www.modifikasi.com/forumdisplay.php/126-Honda",
               "http://www.modifikasi.com/forumdisplay.php/203-Hummer",
               "http://www.modifikasi.com/forumdisplay.php/127-Hyundai",
               "http://www.modifikasi.com/forumdisplay.php/128-Isuzu",
               "http://www.modifikasi.com/forumdisplay.php/129-Jaguar",
               "http://www.modifikasi.com/forumdisplay.php/210-Jeep",
               "http://www.modifikasi.com/forumdisplay.php/130-Kia",
               "http://www.modifikasi.com/forumdisplay.php/482-Lamborghini",
               "http://www.modifikasi.com/forumdisplay.php/204-Land-Rover",
               "http://www.modifikasi.com/forumdisplay.php/131-Lexus",
               "http://www.modifikasi.com/forumdisplay.php/483-Lotus",
               "http://www.modifikasi.com/forumdisplay.php/484-Maserati",
               "http://www.modifikasi.com/forumdisplay.php/132-Mazda",
               "http://www.modifikasi.com/forumdisplay.php/485-McLaren",
               "http://www.modifikasi.com/forumdisplay.php/133-Mercedes-Benz",
               "http://www.modifikasi.com/forumdisplay.php/205-Mini",
               "http://www.modifikasi.com/forumdisplay.php/134-Mitsubishi",
               "http://www.modifikasi.com/forumdisplay.php/135-Nissan",
               "http://www.modifikasi.com/forumdisplay.php/141-Opel",
               "http://www.modifikasi.com/forumdisplay.php/486-Porsche",
               "http://www.modifikasi.com/forumdisplay.php/136-Peugeot",
               "http://www.modifikasi.com/forumdisplay.php/487-Renault",
               "http://www.modifikasi.com/forumdisplay.php/206-Proton",
               "http://www.modifikasi.com/forumdisplay.php/488-Rolls-Royce",
               "http://www.modifikasi.com/forumdisplay.php/489-Smart",
               "http://www.modifikasi.com/forumdisplay.php/145-Subaru",
               "http://www.modifikasi.com/forumdisplay.php/145-Subaru",
               "http://www.modifikasi.com/forumdisplay.php/202-Timor",
               "http://www.modifikasi.com/forumdisplay.php/138-Toyota",
               "http://www.modifikasi.com/forumdisplay.php/139-VolksWagen",
               "http://www.modifikasi.com/forumdisplay.php/140-Volvo",
               "http://www.modifikasi.com/forumdisplay.php/142-Merk-Lainnya",
               "http://www.modifikasi.com/forumdisplay.php/417-Diecast-RC-etc",
               "http://www.modifikasi.com/forumdisplay.php/62-Komunitas-amp-Regional",
               "http://www.modifikasi.com/forumdisplay.php/527-Mercedes-Benz-W204-Community-Indonesia",
               "http://www.modifikasi.com/forumdisplay.php/146-Auto-Club",
               "http://www.modifikasi.com/forumdisplay.php/250-Jabodetabek",
               "http://www.modifikasi.com/forumdisplay.php/251-Aceh",
               "http://www.modifikasi.com/forumdisplay.php/252-Bali",
               "http://www.modifikasi.com/forumdisplay.php/253-Bandung",
               "http://www.modifikasi.com/forumdisplay.php/254-Batam",
               "http://www.modifikasi.com/forumdisplay.php/257-Medan",
               "http://www.modifikasi.com/forumdisplay.php/258-Padang",
               "http://www.modifikasi.com/forumdisplay.php/256-Malang",
               "http://www.modifikasi.com/forumdisplay.php/261-Surabaya",
               "http://www.modifikasi.com/forumdisplay.php/260-Semarang",
               "http://www.modifikasi.com/forumdisplay.php/259-Palembang",
               "http://www.modifikasi.com/forumdisplay.php/367-Pekanbaru",
               "http://www.modifikasi.com/forumdisplay.php/255-Lampung",
               "http://www.modifikasi.com/forumdisplay.php/255-Lampung",
               "http://www.modifikasi.com/forumdisplay.php/263-Kalimantan",
               "http://www.modifikasi.com/forumdisplay.php/264-Sulawesi",
               "http://www.modifikasi.com/forumdisplay.php/265-Luar-Negeri",
               "http://www.modifikasi.com/forumdisplay.php/266-Lain-Lainnya",
               "http://www.modifikasi.com/forumdisplay.php/5-Diskusi-Audio-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/12-Diskusi-Head-Unit-amp-Processor",
               "http://www.modifikasi.com/forumdisplay.php/15-Diskusi-Speaker",
               "http://www.modifikasi.com/forumdisplay.php/13-Diskusi-Power-Amplifier",
               "http://www.modifikasi.com/forumdisplay.php/14-Diskusi-Subwoofer",
               "http://www.modifikasi.com/forumdisplay.php/20-Diskusi-Monitor",
               "http://www.modifikasi.com/forumdisplay.php/21-Diskusi-Crossover",
               "http://www.modifikasi.com/forumdisplay.php/23-Diskusi-Instalasi",
               "http://www.modifikasi.com/forumdisplay.php/36-Diskusi-Reference-Song",
               "http://www.modifikasi.com/forumdisplay.php/22-Diskusi-Audio-Lainnya",
               "http://www.modifikasi.com/forumdisplay.php/490-Review-Produk-Audio-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/440-Tips-amp-Artikel-Audio-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/68-Cartens-Autosound",
               "http://www.modifikasi.com/forumdisplay.php/523-Cartens-Store",
               "http://www.modifikasi.com/forumdisplay.php/529-Concerto-Audio",
               "http://www.modifikasi.com/forumdisplay.php/117-UnSCAC-Hwely-Audio",
               "http://www.modifikasi.com/forumdisplay.php/333-Venom",
               "http://www.modifikasi.com/forumdisplay.php/18-Diskusi-Mesin",
               "http://www.modifikasi.com/forumdisplay.php/441-Tips-amp-Artikel-Mesin-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/491-Review-Produk-Mesin-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/112-Airboom-amp-JDM-Parts",
               "http://www.modifikasi.com/forumdisplay.php/279-Asco-Motorsport",
               "http://www.modifikasi.com/forumdisplay.php/427-CRC-Indonesia",
               "http://www.modifikasi.com/forumdisplay.php/67-de-Auto-Motorsport",
               "http://www.modifikasi.com/forumdisplay.php/528-RaceChip-Chiptuning-Indonesia",
               "http://www.modifikasi.com/forumdisplay.php/530-Rexco-Indonesia",
               "http://www.modifikasi.com/forumdisplay.php/97-Simota-Racing-Sports",
               "http://www.modifikasi.com/forumdisplay.php/198-Speed-Z-Performance",
               "http://www.modifikasi.com/forumdisplay.php/17-Diskusi-Eksterior",
               "http://www.modifikasi.com/forumdisplay.php/444-Tips-amp-Artikel-Eksterior-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/494-Review-Produk-Eksterior-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/323-Eagle-Eyes",
               "http://www.modifikasi.com/forumdisplay.php/19-Diskusi-Knalpot",
               "http://www.modifikasi.com/forumdisplay.php/442-Tips-amp-Artikel-Knalpot-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/492-Review-Produk-Knalpot-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/24-Diskusi-Kaki-Kaki",
               "http://www.modifikasi.com/forumdisplay.php/443-Tips-amp-Artikel-Kaki-Kaki-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/493-Review-Produk-Kaki-Kaki-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/43-D2-Concept",
               "http://www.modifikasi.com/forumdisplay.php/387-Das-Beste-Motorsport-Indonesia",
               "http://www.modifikasi.com/forumdisplay.php/25-Diskusi-Interior",
               "http://www.modifikasi.com/forumdisplay.php/445-Tips-amp-Artikel-Interior-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/495-Review-Produk-Interior-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/26-Diskusi-Aksesoris",
               "http://www.modifikasi.com/forumdisplay.php/446-Tips-amp-Artikel-Aksesoris-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/48-Delapan-Satu",
               "http://www.modifikasi.com/forumdisplay.php/72-HID-Provision",
               "http://www.modifikasi.com/forumdisplay.php/344-Diskusi-Perawatan-Mobil-(Exterior-amp-Interior)",
               "http://www.modifikasi.com/forumdisplay.php/447-Tips-amp-Artikel-Perawatan-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/497-Review-Produk-Perawatan-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/428-Clean-N-Tidy",
               "http://www.modifikasi.com/forumdisplay.php/522-HD-Car-Care-Indonesia",
               "http://www.modifikasi.com/forumdisplay.php/510-Scuto-Laminating-Mobil",
               "http://www.modifikasi.com/forumdisplay.php/290-Rawatmobilmu",
               "http://www.modifikasi.com/forumdisplay.php/31-Diskusi-Otomotif-Lain-Lainnya",
               "http://www.modifikasi.com/forumdisplay.php/448-Tips-amp-Artikel-Otomotif-Lainnya",
               "http://www.modifikasi.com/forumdisplay.php/498-Review-Produk-Otomotif-Lainnya",
               "http://www.modifikasi.com/forumdisplay.php/532-ERA-Motor",
               "http://www.modifikasi.com/forumdisplay.php/10-Peraturan-amp-Informasi",
               "http://www.modifikasi.com/forumdisplay.php/16-Saran-Kritik-amp-Pertanyaan",
               "http://www.modifikasi.com/forumdisplay.php/425-Diskusi-Seputar-Giro-Modcom",
               "http://www.modifikasi.com/forumdisplay.php/426-Transaksi-Giro-Bermasalah",
               "http://www.modifikasi.com/forumdisplay.php/32-Automotive",
               "http://www.modifikasi.com/forumdisplay.php/371-Finance",
               "http://www.modifikasi.com/forumdisplay.php/434-Gadget",
               "http://www.modifikasi.com/forumdisplay.php/435-Games",
               "http://www.modifikasi.com/forumdisplay.php/372-Health",
               "http://www.modifikasi.com/forumdisplay.php/373-Jokes",
               "http://www.modifikasi.com/forumdisplay.php/436-Kriminal",
               "http://www.modifikasi.com/forumdisplay.php/374-LifeStyle",
               "http://www.modifikasi.com/forumdisplay.php/375-Movie",
               "http://www.modifikasi.com/forumdisplay.php/376-Music",
               "http://www.modifikasi.com/forumdisplay.php/377-Politik",
               "http://www.modifikasi.com/forumdisplay.php/437-Pro-Kontra",
               "http://www.modifikasi.com/forumdisplay.php/438-Properti",
               "http://www.modifikasi.com/forumdisplay.php/378-ShowBiz",
               "http://www.modifikasi.com/forumdisplay.php/379-Sports",
               "http://www.modifikasi.com/forumdisplay.php/380-Technology",
               "http://www.modifikasi.com/forumdisplay.php/439-Tokoh",
               "http://www.modifikasi.com/forumdisplay.php/381-Travel",
               "http://www.modifikasi.com/forumdisplay.php/382-Umbrella-Girls",
               "http://www.modifikasi.com/forumdisplay.php/383-Lain-Lainnya"
          ]                         
     COUNTRY = "IDN"
     THREAD_XPATH = "//ol//li[re:test(@id,'thread*')]"
     THREAD_LINK_XPATH = ".//h3[@class='threadtitle']//a[@class='title']/@href"
     LAST_PAGE_XPATH = "//span[@class='first_last']/a/@href"
     PREV_XPATH = "//span[@class='prev_next']/a[@rel='prev']/@href"
     POST_XPATH = "//ol//li[re:test(@id,'post_*')]"
     FIELDS = [
          {"published_date": {
               "single": True, 
               "data_type": "date", 
               "concat": True, 
               "xpath": ".//span[@class='date']//text()"
          }},
          {"permalink": {
               "single": True, 
               "data_type": "url", 
               "concat": False, 
               "xpath": ".//span[@class='nodecontrols']/a[re:test(@name,'post*')]/@href"
          }},
          {"author_name":{
               "single":True,
               "data_type": "string",
               "concat":False,
               "xpath":".//a[re:test(@class,'username')]//text()"
          }},
          {"content":{
               "single":True,
               "data_type": "string",
               "concat":True,
               "xpath":".//div[@class='postbody']//div[re:test(@class,'postrow')]//text()"
          }},
          {"title":{
               "single":True,
               "data_type": "string",
               "concat":False,
               "xpath":"//span[re:test(@class,'threadtitle')]//text()"
          }}
     ]
     CONDITIONS={
          "has_to_have_content":{
               "condition":'"content" in document',
               "exception":'"Content is not defined"'
          },
          "content_cannot_be_empty":{
               "condition":'len(document["content"]) > 0',
               "exception":'"Content cannot be empty"'
          }
     }
#end class
